# config.toml

# ==================== 基础设置 ====================

# 下载模式选择
# 'GET_ALL': 传统模式，一次性获取所有动态URL。
# 'ITERATIVE': 迭代模式，边获取边处理（推荐）。
download_mode = "ITERATIVE"

# 增量下载开关
# 如果设为 true，遇到已存在的动态时会停止下载该用户后续内容
incremental_download = false

# ==================== 路径设置 ====================

# Cookie 文件路径
cookie_file_path = 'C:\Base1.5-美女图片\bili\gallery-dl\bilibili_cookies.txt'

# 图片和元数据保存的基础输出目录
output_dir_path = 'C:\Base1.5-美女图片\bili\gallery-dl\bilibili_images'

# ==================== 用户列表 ====================

# 要下载的用户数字ID列表
users_id = [
            # 27534330,  # 崩坏3第一偶像爱酱
        #1340190821, # 崩坏星穹铁道
        #1636034895, # 绝区零
    # 已经重新运行下载完live_photo的
    # 35117822,   # 好喜欢蜜桃四季春
    # 10982073,   # 明前奶粉罐
    # 560647,     # 坂坂白


    2075682,    # Kitaro绮太郎
    31968078,   # 粽子淞
    4096581,    # 病院坂saki
    305956876,  # 腥味猫罐
    3461567555307880, # 羲拉C3C
    555683603,  # 玛丽兰想当玛丽苏
    3546937055775240, # Yasal_170
    3546938211305491, # beatberry314
    356010767,  # 走路摇ZLY
    836885,     # 清和Alicia
    21876627,   # 谢安然
    498099165,  # 一颗小兔娘
    210752,     # 真栗
    100201761,  # 听霜_
    16322326,   # 丝言不吃包子
    9293142,    # 宫本樱樱酱
]

# ==================== 用户映射 ====================

# 用户ID到文件夹名称的手动映射
# 格式: "ID" = "文件夹名"
[user_id_map]
"1340190821" = "崩坏星穹铁道"
"27534330" = "崩坏3第一偶像爱酱"
"1636034895" = "绝区零"
"560647" = "坂坂白"
"2075682" = "Kitaro绮太郎"
"31968078" = "粽子淞"
"4096581" = "病院坂saki"
"35117822" = "好喜欢蜜桃四季春"
"305956876" = "腥味猫罐"
"10982073" = "明前奶粉罐"
"3461567555307880" = "羲拉C3C"
"555683603" = "玛丽兰想当玛丽苏"
"3546937055775240" = "Yasal"
"3546938211305491" = "beatberry314"
"356010767" = "走路摇ZLY"
"836885" = "清和Alicia"
"21876627" = "谢安然"
"498099165" = "一颗小兔娘"
"210752" = "真栗"
"100201761" = "听霜"
"16322326" = "丝言不吃包子"
"9293142" = "宫本樱樱酱"